language: android
jdk: oraclejdk8
sudo: false
android:
  components:
     - tools
     - platform-tools
     - build-tools-25.0.1
     - android-25
     - extra-google-m2repository
     - extra-android-m2repository
cache:
  directories:
  - "$HOME/.gradle/caches/"
script:
- "./gradlew build"
deploy:
  provider: script
  script: "./gradlew bintrayUpload"
  on:
    tags: true
env:
  global:
    secure: "b3o1H56Kya5DPmz4zQXdyWKgHnskOHjyjq2EOowcOTo9XDk7FV8pViQRAC1ZGqC8V+D9BS8QApyzH9LxQI7W7IwQt0C8ECTEC4YmiqfFIojpfLBsvmhkCoSDVNOELKcffQVd/MCEKGk93ClwxPb2pxt2m/ZJ3qYuixRCoF9GOKA14ck7Ay5wE8dGqTggefUrpK3XQJjutiQmUlLKuYqV1JJDRAM+UkylomPSXyJZN3W/by/GK20RmjZ90j2vuIyyAlaEOF6yyFyzH1CtG5H1NuDR38HlOySUxzgUg1x/4+ynOhmSeHUh6Oct8BAGPdksUF/GmygL/tXlCjQPmfHwBjyKJQqaM+KT3rgN1rTovpuU/lKwkD8FlUokQOVdV0rvMDFLdo/LJ1iRkki6gZTuMFKROPmhBmlbJm9N0NpSDhkhhUNzfiFU/WcCkSD5nYhlEdOmLBpvlj4OOdk8pwCtqo67O+sJlNgoqjAZW1F8pweN+vvHFD7052zRtHF9EUyxfnlyZ5tjv1M7KmbUBHuH3cMU9MX8oWnKuXL+qLRZpgvmovxJbfMefpXuhC9hKsTQuvFp1FOaevTTp78ICg2JD/CSHoBizefGJm6juCzGQ3PfCnj1ImqCIxd4gqCaa2DS6AOVkENGBdfgfqnhs5Kx87Gsh+sUHLw9yUYZ6Z6YppA="
